simulacion:
  ancho_mapa: 8
  alto_mapa: 8
  pasos_total: 30  # Aumentar para ver mejor las gráficas
  delay_paso: 0.5  # Reducir delay para mejor visualización
  mostrar_mapa: true

agentes:
  - id: 1
    perfil: guardian
    posicion: [0, 0]
    color: blue
    
  - id: 2
    perfil: explorador
    posicion: [7, 0]
    color: red
    
  - id: 3
    perfil: soporte
    posicion: [0, 7]
    color: green

amenazas:
  probabilidad: 0.3  # Aumentar probabilidad de amenazas
  intensidad_maxima: 0.9
