agentes:
  - id: 1
    perfil: guardian_perimetro
    posicion_inicial: [0, 0]
    config:
      radio_comunicacion: 3
      velocidad_movimiento: 1
      habilidades_especiales: 
        - deteccion_temprana
        - conocimiento_perimetro
      experiencia_base: 5
      
  - id: 2
    perfil: explorador_riesgo
    posicion_inicial: [9, 0]
    config:
      radio_comunicacion: 6
      velocidad_movimiento: 2
      habilidades_especiales: 
        - evaluacion_riesgos
        - exploracion_avanzada
      experiencia_base: 4
      
  - id: 3
    perfil: coordinador
    posicion_inicial: [5, 5]
    config:
      radio_comunicacion: 8
      velocidad_movimiento: 1
      habilidades_especiales: 
        - comando
        - estrategia
      experiencia_base: 6
      
  - id: 4
    perfil: soporte_rapido
    posicion_inicial: [0, 9]
    config:
      radio_comunicacion: 5
      velocidad_movimiento: 3
      habilidades_especiales: 
        - primeros_auxilios
        - rescate_rapido
      experiencia_base: 5
      
  - id: 5
    perfil: observador
    posicion_inicial: [9, 9]
    config:
      radio_comunicacion: 8
      velocidad_movimiento: 1
      habilidades_especiales: 
        - analisis_datos
        - monitoreo_continuo
      experiencia_base: 4

configuracion_general:
  radio_maximo_comunicacion: 10
  velocidad_maxima_movimiento: 3
  umbral_salud_critica: 0.3
  tiempo_maximo_emergencia: 10
