dimensiones:
  ancho: 10
  alto: 10
  celdas_totales: 100

zonas_especiales:
  perimetro:
    - [0, 0]
    - [0, 9]
    - [9, 0]
    - [9, 9]
    - [0, 4]
    - [9, 4]
    - [4, 0]
    - [4, 9]

  puntos_calientes:
    - [2, 2]
    - [7, 7]
    - [2, 7]
    - [7, 2]
    - [5, 5]

  areas_criticas:
    - [3, 3]
    - [6, 6]
    - [3, 6]
    - [6, 3]

  bases_operativas:
    - [0, 0]
    - [9, 9]
    - [5, 5]

configuracion_visual:
  color_perimetro: "#FF6B6B"
  color_puntos_calientes: "#FFE66D"
  color_areas_criticas: "#4ECDC4"
  color_bases: "#1A535C"
  color_neutral: "#F7FFF7"

probabilidades_amenaza:
  base: 0.1
  multiplicador_perimetro: 1.5
  multiplicador_puntos_calientes: 2.0
  multiplicador_areas_criticas: 1.8
  propagacion: 0.3
